---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-providers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bmutziu/gitops.git'
    path: platform/providers
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 2
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 5m0s
