apiVersion: azure.platformref.crossplane.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: platform-ref-azure-db
  namespace: dev
spec:
  parameters:
    storageGB: 5 #Minimum value is 5
    clusterRef:
      id: bmutziu-platform-ref-azure #This field must match the cluster XR spec.id
  writeConnectionSecretToRef:
    name: platform-ref-azure-db-conn #Must be unique for each instance
