apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-ref-azure
spec:
  ignoreCrossplaneConstraints: false
  package: docker.io/bmutziu/platform-ref-azure:v0.4.0-1.g0e95256
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
  
