apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: platform-ref-azure
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  ignoreCrossplaneConstraints: false
  package: docker.io/bmutziu/platform-ref-azure:v0.5.0-9.g4dca519
  packagePullPolicy: Always
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
  
