---
apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: dev
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: azure-account-creds
      key: credentials
