apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-azure
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ignoreCrossplaneConstraints: false
  package: registry.upbound.io/crossplane/provider-azure:v0.18.1
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
